Update main.js for using callbacks
wirecloud-fiware/sth-source-operator pull request #1
Opened 2017-08-11 11:28 UTC by osfrance

Conformely to the widget API doc (https://wirecloud.readthedocs.io/en/stable/widgetapi/widgetapi/#widget-api), changing function mp.http.makeRequest() for use Callbacks (OnFailure, OnSucess and OnComplete.

2017-08-18 08:05 UTC, aarranz requested changes

2017-08-18 08:05 UTC, aarranz commented on src/js/main.js
> +                onComplete: function () {
`onComplete` doesn't provide a reason parameter. I think what you wanted to write is:

```javascript
                onException: function(reason) {
                        mp.operator.log(reason);
                }
```

2017-08-18 08:05 UTC, aarranz commented on src/js/main.js
> +                        var data = JSON.parse(response.responseText).contextResponses[0].contextElement.attributes[0].values;
`onSuccess` only checks if the status code returned by the server is in the 2xx range. Probably this method can be improved by checking if the response uses the expected status code:

```javascript
            if (response.status !== 200) {
                throw new Error('Unexpected response from STH');
            }
```

2017-09-08 13:21 UTC, merged

2017-09-08 13:30 UTC, aarranz commented
Merged. Thank you very much for your contribution.

2017-09-18 06:42 UTC, osfrance commented
Your welcome !